### ISSUE TITLE
Recursive function check should be able to take in which functionName SHOULD be recursive

### ISSUE THREAD

**Issue by Animanny** [Animanny/ECE496-Aggregation-Page#7]

**Comment by majanojoel** [comment]
Done in https://github.com/majanojoel/ECE496_ClangPlugins/commit/7b7979ebe86a50cde49b15e743ef30ba093ea113. Just needs to be compiled on 15.0.7 and integrated into script and website configurator.

**Comment by majanojoel** [comment]
Verified fix by the latest commit in https://github.com/majanojoel/ECE496_ClangPlugins.
