### ISSUE TITLE
runner_script.py should be able to auto detect if we are using C or C++ files

### ISSUE THREAD

**Issue by majanojoel** [Animanny/ECE496-Aggregation-Page#9]

**Comment by Animanny** [comment]
Can you just look at the file extension?

**Comment by majanojoel** [comment]
Yes, i think the fix is just creating two lists of C and C++ files (rn we only create a list for C++ src files), whichever one is not empty that's the extension used. If we get a mix of both we just say that's not allowed.

**Comment by majanojoel** [comment]
Fixed by commit 4b903c8
